### PR TITLE
Switched the data access from in_memory DAO  to full DAO, Added the W…

### PR DESCRIPTION
**Pull request by Mahan-H**
Switched the data access from in_memory DAO  to full DAO, Added the Welcome Page, Added Functionality to the goBack button on the signUp and logIn page, Improved the GUI of the Welcome page.

### CODE REVIEW

**Comment by Divnoor-C** [comment]
Next we need to add the fact that the username needs to be an email only.

**Review by ChristopherHanRoy — COMMENTED** [review]
Looks good Mahan! Make sure to write javadocs for all methods

**Comment by Divnoor-C** [comment]
Remove unnecessary WelcomeState class.

**Comment by shahkabir1** [comment]
Going to add Email Authentication functionality using Java Mail and an SMTP perhaps; also switching username to email to allow for easier authentication and account creation

**Pull request merged**
